/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppDataRouteImport } from './routes/app-data'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusRouteImport } from './routes/bus'
import { Route as FilenameRouteImport } from './routes/filename'
import { Route as HealthRouteImport } from './routes/health'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as SummarizeRouteImport } from './routes/summarize'
import { Route as WordsmithRouteImport } from './routes/wordsmith'
import { Route as DocsIdRouteImport } from './routes/docs/$id'
import { Route as DocsPublishRouteImport } from './routes/docs/publish'
import { Route as MemoryUserIdRouteImport } from './routes/memory.$userId'
import { Route as ToolsNameRouteImport } from './routes/tools/$name'
import { Route as ToolsOpenapiDotjsonRouteImport } from './routes/tools/openapi[.]json'
import { Route as DocsIdSlugRouteImport } from './routes/docs/$id.$slug'
import { Route as DocsMdIdRouteImport } from './routes/docs/md.$id'
import { Route as ResponsesClipboardIdRouteImport } from './routes/responses/clipboard.$id'
import { Route as ResponsesMdIdRouteImport } from './routes/responses/md.$id'
import { Route as ResponsesResultIdRouteImport } from './routes/responses/result.$id'
import { Route as ResponsesViewIdRouteImport } from './routes/responses/view.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/app-data',
  path: '/app-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusRoute = BusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => rootRouteImport,
} as any)
const FilenameRoute = FilenameRouteImport.update({
  id: '/filename',
  path: '/filename',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const SummarizeRoute = SummarizeRouteImport.update({
  id: '/summarize',
  path: '/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsmithRoute = WordsmithRouteImport.update({
  id: '/wordsmith',
  path: '/wordsmith',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIdRoute = DocsIdRouteImport.update({
  id: '/docs/$id',
  path: '/docs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPublishRoute = DocsPublishRouteImport.update({
  id: '/docs/publish',
  path: '/docs/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryUserIdRoute = MemoryUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => MemoryRoute,
} as any)
const ToolsNameRoute = ToolsNameRouteImport.update({
  id: '/tools/$name',
  path: '/tools/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsOpenapiDotjsonRoute = ToolsOpenapiDotjsonRouteImport.update({
  id: '/tools/openapi.json',
  path: '/tools/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIdSlugRoute = DocsIdSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsIdRoute,
} as any)
const DocsMdIdRoute = DocsMdIdRouteImport.update({
  id: '/docs/md/$id',
  path: '/docs/md/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsesClipboardIdRoute = ResponsesClipboardIdRouteImport.update({
  id: '/responses/clipboard/$id',
  path: '/responses/clipboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsesMdIdRoute = ResponsesMdIdRouteImport.update({
  id: '/responses/md/$id',
  path: '/responses/md/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsesResultIdRoute = ResponsesResultIdRouteImport.update({
  id: '/responses/result/$id',
  path: '/responses/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsesViewIdRoute = ResponsesViewIdRouteImport.update({
  id: '/responses/view/$id',
  path: '/responses/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/app-data': typeof AppDataRoute
  '/auth': typeof AuthRoute
  '/bus': typeof BusRoute
  '/filename': typeof FilenameRoute
  '/health': typeof HealthRoute
  '/memory': typeof MemoryRouteWithChildren
  '/summarize': typeof SummarizeRoute
  '/wordsmith': typeof WordsmithRoute
  '/docs/$id': typeof DocsIdRouteWithChildren
  '/docs/publish': typeof DocsPublishRoute
  '/memory/$userId': typeof MemoryUserIdRoute
  '/tools/$name': typeof ToolsNameRoute
  '/tools/openapi.json': typeof ToolsOpenapiDotjsonRoute
  '/docs/$id/$slug': typeof DocsIdSlugRoute
  '/docs/md/$id': typeof DocsMdIdRoute
  '/responses/clipboard/$id': typeof ResponsesClipboardIdRoute
  '/responses/md/$id': typeof ResponsesMdIdRoute
  '/responses/result/$id': typeof ResponsesResultIdRoute
  '/responses/view/$id': typeof ResponsesViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/app-data': typeof AppDataRoute
  '/auth': typeof AuthRoute
  '/bus': typeof BusRoute
  '/filename': typeof FilenameRoute
  '/health': typeof HealthRoute
  '/memory': typeof MemoryRouteWithChildren
  '/summarize': typeof SummarizeRoute
  '/wordsmith': typeof WordsmithRoute
  '/docs/$id': typeof DocsIdRouteWithChildren
  '/docs/publish': typeof DocsPublishRoute
  '/memory/$userId': typeof MemoryUserIdRoute
  '/tools/$name': typeof ToolsNameRoute
  '/tools/openapi.json': typeof ToolsOpenapiDotjsonRoute
  '/docs/$id/$slug': typeof DocsIdSlugRoute
  '/docs/md/$id': typeof DocsMdIdRoute
  '/responses/clipboard/$id': typeof ResponsesClipboardIdRoute
  '/responses/md/$id': typeof ResponsesMdIdRoute
  '/responses/result/$id': typeof ResponsesResultIdRoute
  '/responses/view/$id': typeof ResponsesViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/app-data': typeof AppDataRoute
  '/auth': typeof AuthRoute
  '/bus': typeof BusRoute
  '/filename': typeof FilenameRoute
  '/health': typeof HealthRoute
  '/memory': typeof MemoryRouteWithChildren
  '/summarize': typeof SummarizeRoute
  '/wordsmith': typeof WordsmithRoute
  '/docs/$id': typeof DocsIdRouteWithChildren
  '/docs/publish': typeof DocsPublishRoute
  '/memory/$userId': typeof MemoryUserIdRoute
  '/tools/$name': typeof ToolsNameRoute
  '/tools/openapi.json': typeof ToolsOpenapiDotjsonRoute
  '/docs/$id/$slug': typeof DocsIdSlugRoute
  '/docs/md/$id': typeof DocsMdIdRoute
  '/responses/clipboard/$id': typeof ResponsesClipboardIdRoute
  '/responses/md/$id': typeof ResponsesMdIdRoute
  '/responses/result/$id': typeof ResponsesResultIdRoute
  '/responses/view/$id': typeof ResponsesViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app-data'
    | '/auth'
    | '/bus'
    | '/filename'
    | '/health'
    | '/memory'
    | '/summarize'
    | '/wordsmith'
    | '/docs/$id'
    | '/docs/publish'
    | '/memory/$userId'
    | '/tools/$name'
    | '/tools/openapi.json'
    | '/docs/$id/$slug'
    | '/docs/md/$id'
    | '/responses/clipboard/$id'
    | '/responses/md/$id'
    | '/responses/result/$id'
    | '/responses/view/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app-data'
    | '/auth'
    | '/bus'
    | '/filename'
    | '/health'
    | '/memory'
    | '/summarize'
    | '/wordsmith'
    | '/docs/$id'
    | '/docs/publish'
    | '/memory/$userId'
    | '/tools/$name'
    | '/tools/openapi.json'
    | '/docs/$id/$slug'
    | '/docs/md/$id'
    | '/responses/clipboard/$id'
    | '/responses/md/$id'
    | '/responses/result/$id'
    | '/responses/view/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app-data'
    | '/auth'
    | '/bus'
    | '/filename'
    | '/health'
    | '/memory'
    | '/summarize'
    | '/wordsmith'
    | '/docs/$id'
    | '/docs/publish'
    | '/memory/$userId'
    | '/tools/$name'
    | '/tools/openapi.json'
    | '/docs/$id/$slug'
    | '/docs/md/$id'
    | '/responses/clipboard/$id'
    | '/responses/md/$id'
    | '/responses/result/$id'
    | '/responses/view/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AppDataRoute: typeof AppDataRoute
  AuthRoute: typeof AuthRoute
  BusRoute: typeof BusRoute
  FilenameRoute: typeof FilenameRoute
  HealthRoute: typeof HealthRoute
  MemoryRoute: typeof MemoryRouteWithChildren
  SummarizeRoute: typeof SummarizeRoute
  WordsmithRoute: typeof WordsmithRoute
  DocsIdRoute: typeof DocsIdRouteWithChildren
  DocsPublishRoute: typeof DocsPublishRoute
  ToolsNameRoute: typeof ToolsNameRoute
  ToolsOpenapiDotjsonRoute: typeof ToolsOpenapiDotjsonRoute
  DocsMdIdRoute: typeof DocsMdIdRoute
  ResponsesClipboardIdRoute: typeof ResponsesClipboardIdRoute
  ResponsesMdIdRoute: typeof ResponsesMdIdRoute
  ResponsesResultIdRoute: typeof ResponsesResultIdRoute
  ResponsesViewIdRoute: typeof ResponsesViewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-data': {
      id: '/app-data'
      path: '/app-data'
      fullPath: '/app-data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus': {
      id: '/bus'
      path: '/bus'
      fullPath: '/bus'
      preLoaderRoute: typeof BusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filename': {
      id: '/filename'
      path: '/filename'
      fullPath: '/filename'
      preLoaderRoute: typeof FilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summarize': {
      id: '/summarize'
      path: '/summarize'
      fullPath: '/summarize'
      preLoaderRoute: typeof SummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wordsmith': {
      id: '/wordsmith'
      path: '/wordsmith'
      fullPath: '/wordsmith'
      preLoaderRoute: typeof WordsmithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$id': {
      id: '/docs/$id'
      path: '/docs/$id'
      fullPath: '/docs/$id'
      preLoaderRoute: typeof DocsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/publish': {
      id: '/docs/publish'
      path: '/docs/publish'
      fullPath: '/docs/publish'
      preLoaderRoute: typeof DocsPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/$userId': {
      id: '/memory/$userId'
      path: '/$userId'
      fullPath: '/memory/$userId'
      preLoaderRoute: typeof MemoryUserIdRouteImport
      parentRoute: typeof MemoryRoute
    }
    '/tools/$name': {
      id: '/tools/$name'
      path: '/tools/$name'
      fullPath: '/tools/$name'
      preLoaderRoute: typeof ToolsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/openapi.json': {
      id: '/tools/openapi.json'
      path: '/tools/openapi.json'
      fullPath: '/tools/openapi.json'
      preLoaderRoute: typeof ToolsOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$id/$slug': {
      id: '/docs/$id/$slug'
      path: '/$slug'
      fullPath: '/docs/$id/$slug'
      preLoaderRoute: typeof DocsIdSlugRouteImport
      parentRoute: typeof DocsIdRoute
    }
    '/docs/md/$id': {
      id: '/docs/md/$id'
      path: '/docs/md/$id'
      fullPath: '/docs/md/$id'
      preLoaderRoute: typeof DocsMdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responses/clipboard/$id': {
      id: '/responses/clipboard/$id'
      path: '/responses/clipboard/$id'
      fullPath: '/responses/clipboard/$id'
      preLoaderRoute: typeof ResponsesClipboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responses/md/$id': {
      id: '/responses/md/$id'
      path: '/responses/md/$id'
      fullPath: '/responses/md/$id'
      preLoaderRoute: typeof ResponsesMdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responses/result/$id': {
      id: '/responses/result/$id'
      path: '/responses/result/$id'
      fullPath: '/responses/result/$id'
      preLoaderRoute: typeof ResponsesResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responses/view/$id': {
      id: '/responses/view/$id'
      path: '/responses/view/$id'
      fullPath: '/responses/view/$id'
      preLoaderRoute: typeof ResponsesViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MemoryRouteChildren {
  MemoryUserIdRoute: typeof MemoryUserIdRoute
}

const MemoryRouteChildren: MemoryRouteChildren = {
  MemoryUserIdRoute: MemoryUserIdRoute,
}

const MemoryRouteWithChildren =
  MemoryRoute._addFileChildren(MemoryRouteChildren)

interface DocsIdRouteChildren {
  DocsIdSlugRoute: typeof DocsIdSlugRoute
}

const DocsIdRouteChildren: DocsIdRouteChildren = {
  DocsIdSlugRoute: DocsIdSlugRoute,
}

const DocsIdRouteWithChildren =
  DocsIdRoute._addFileChildren(DocsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AppDataRoute: AppDataRoute,
  AuthRoute: AuthRoute,
  BusRoute: BusRoute,
  FilenameRoute: FilenameRoute,
  HealthRoute: HealthRoute,
  MemoryRoute: MemoryRouteWithChildren,
  SummarizeRoute: SummarizeRoute,
  WordsmithRoute: WordsmithRoute,
  DocsIdRoute: DocsIdRouteWithChildren,
  DocsPublishRoute: DocsPublishRoute,
  ToolsNameRoute: ToolsNameRoute,
  ToolsOpenapiDotjsonRoute: ToolsOpenapiDotjsonRoute,
  DocsMdIdRoute: DocsMdIdRoute,
  ResponsesClipboardIdRoute: ResponsesClipboardIdRoute,
  ResponsesMdIdRoute: ResponsesMdIdRoute,
  ResponsesResultIdRoute: ResponsesResultIdRoute,
  ResponsesViewIdRoute: ResponsesViewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
